### ISSUE TITLE
Phinch not installing on Mac

### ISSUE THREAD

**Issue by Santab111** [PhinchApp/Phinch#10]
This is the message I get:
<img width="422" alt="Screen Shot 2019-06-06 at 11 21 09 AM" src="https://user-images.githubusercontent.com/51424088/59045235-a85c6e80-884d-11e9-91dc-3bd9397e1791.png">
I have tried several mac systems. Please help!

**Comment by hollybik** [comment]
Can you post some more information here about your Mac OS X (are you using the latest Mojave OS) as well as the browsers you've tried (looks like you tried to download with Firefox - have you also tried the download via Chrome and Safari)? The Phinch App should be security certified with developer credentials, and this is the first report we've had of this error message.

**Comment by Santab111** [comment]
<img width="422" alt="Screen Shot 2019-06-13 at 12 57 44 PM" src="https://user-images.githubusercontent.com/51424088/59452032-dc4e0b80-8dda-11e9-85b0-cca8f98e65c3.png">
I haven't tried chrome yet, but safari download still gives me the error. And yes- I have Mojave:
<img width="589" alt="Screen Shot 2019-06-13 at 12 58 52 PM" src="https://user-images.githubusercontent.com/51424088/59452142-14554e80-8ddb-11e9-91de-11a1bf4e0a30.png">
