### ISSUE TITLE
Visualisation only showing Phyla level and not class, order, family, genus, etc 

### ISSUE THREAD

**Issue by dhuyben** [PhinchApp/Phinch#11]
I made a biom file from 16S OTU data in Mothur using the Silva database. The file imports fine, but when I visualise the data, it only shows the Phyla level and there is not button to select the other levels (eg Order). 

Is there a problem since I used the Silva instead of Greengenes database? I see that the taxonomy levels are in quotations instead of underscore and I wonder if that is a problem. I don't code in QIIME and I can find any help using Mothur. Any help would be great! Below is the first few lines:

"id":"stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.opti_mcc.shared-0.03",
"format": "Biological   Observation Matrix 0.9.1",
"format_url":   "http://biom-format.org",
"type": "OTU   table",
"generated_by":   "mothur1.42.3",
"date": "Thu Jul 11   13:56:44 2019",
"rows":[
{"id":"Otu00001",   "metadata":{"taxonomy":["Bacteria",   "Firmicutes", "Bacilli", "Bacillales",   "Bacillales_unclassified", "Bacillales_unclassified"],   "bootstrap":[100, 100, 100, 100, 97, 97]}},

**Comment by vebaev** [comment]
Same thing here, showing only 1 level and the level drop-down menu is missing. (the biom is from mothur)

**Comment by mikeschhorn** [comment]
Same thing here - however, import of same mothur biome files that don't work in the new app into the old phinch web-app (https://usegalaxy.eu/phinch/viz.html) show full taxonomy - but there generating images stalles and no option for grouped taxonomy barcharts.....

**Comment by Piplopp** [comment]
Hi, I have the exact same issue and I poked around a bit, the issue of not having the dropdown seems to be because we are missing the prefixes like `k__` before each level.

After adding the same prefixes as the GreenGenes database (`k__, p__, c__, o__...`) I get the taxonomy bar back. If I add arbitrary prefix levels I get all the arbitrary levels just as expected.

If there is no prefixes however it still only shows the first level.

**Comment by Zubyluche** [comment]
Hi dhuyben,

 how did you get your mothur converted Biom file to upload perfectly on Phinch?. When I upload my mothur converted biom file, it throw an error "the file uploaded doesn't validate for phinch". Please, I will need some direction or pointers here.

Thank you

**Comment by dhuyben** [comment]
Hi Zubyluche, I did this a long time ago and I am not an expert. I imagine you did not make the biom file correctly. Maybe you are missing a shared, meta, constaxonomy or other file. Here is the code I used:
make.biom(shared=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.opti_mcc.shared, metadata=stability.meta, constaxonomy=stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.opti_mcc.0.03.cons.taxonomy)

When you open the biom file as text it should look like my first post. You can also find more info here: https://mothur.org/wiki/make.biom/

**Comment by Zubyluche** [comment]
Thank you so much dhuyben. I appreciate your response . I succeeded in
uploading the biom file on phinch but I realized that phinch app doesn't
make different graphs except the bar stacked graph.
