### ISSUE TITLE
Biom format from kraken-biom  is not working

### ISSUE THREAD

**Issue by LeonardosMageiros** [PhinchApp/Phinch#15]
Hi, 

I have analysed some metagenomic samples using Kraken2 and I would like to visualise my taxonomic profiles using Phinch. 
I used the kraken-biom tool (https://github.com/smdabdoub/kraken-biom) to transform the kraken output to biom format but when I upload the files to Phinch the biom files are not validated. 

Have you ever faced this issue before? 
I would appreceate any suggestions

Thank you in advance. 

Best 
Leonardos

**Comment by heather340** [comment]
I am having the same issue. Have you been able to resolve anything? 

Thanks!

**Comment by smdabdoub** [comment]
@LeonardosMageiros @heather340 Hi all, I am the author of kraken-biom. I've recently integrated some code to add metadata to the biom tables created by kraken-biom. This was reported as an issue, and the update should fix the problem you're having.

Shareef
